dataset_params:
  im_path: 'processed_data/'
  im_channels : 1
  im_size : 256
  name: 'medical_image'

diffusion_params:
  num_timesteps : 1000
  beta_start : 0.0015
  beta_end : 0.0195

ldm_params:
  down_channels: [ 256, 384, 512, 768 ]
  mid_channels: [ 768, 512 ]
  down_sample: [ True, True, True ]
  attn_down : [True, True, True]
  time_emb_dim: 512
  norm_channels: 32
  num_heads: 16
  conv_out_channels : 128
  num_down_layers : 2
  num_mid_layers : 2
  num_up_layers : 2
  condition_config:
    condition_types: [ 'image' ]
    image_condition_config:
      image_condition_input_channels: 5
      image_condition_output_channels: 1
      image_condition_h : 256
      image_condition_w : 256
      cond_drop_prob: 0.1


autoencoder_params:
  z_channels: 4
  codebook_size : 8192
  down_channels : [64, 128, 256, 256]
  mid_channels : [256, 256]
  down_sample : [True, True, True]
  attn_down : [False, False, False]
  norm_channels: 32
  num_heads: 8
  num_down_layers : 2
  num_mid_layers : 2
  num_up_layers : 2


train_params:
  seed : 42
  task_name: 'test_try'
  leave_out_subjects: 10
  ldm_batch_size: 36
  autoencoder_batch_size: 12
  reconstruction_weight: 1.0
  disc_start: 40000
  disc_weight: 0.5
  codebook_weight: 1.0
  commitment_beta: 0.25
  perceptual_weight: 1.0
  kl_weight: 0.000005
  ldm_epochs: 100
  autoencoder_epochs: 120
  num_samples: 1
  num_grid_rows: 1
  ldm_lr: 0.000005
  autoencoder_lr: 0.00008
  autoencoder_acc_steps: 3
  autoencoder_img_save_steps: 100
  save_latents : False
  vae_latent_dir_name: 'vae_latents'
  vqvae_latent_dir_name: 'vqvae_latents'
  ldm_ckpt_name: 'ddpm_ckpt.pth'
  vqvae_autoencoder_ckpt_name: 'vqvae_autoencoder_ckpt.pth'
  vae_autoencoder_ckpt_name: 'vae_autoencoder_ckpt.pth'
  vqvae_discriminator_ckpt_name: 'vqvae_discriminator_ckpt.pth'
  vae_discriminator_ckpt_name: 'vae_discriminator_ckpt.pth'
